# Generated by Django 3.1.3 on 2020-11-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_post',
            new_name='date_created',
        ),
    ]
